### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by Aka7tsu4** [mcNuggets1/mg_m9k#2]
[ERROR] addons/mg_m9k-master/lua/autorun/m9k_heavy_weaps.lua:750: '}' expected (to close '{' at line 748) near '<eof>'
1. unknown - addons/mg_m9k-master/lua/autorun/m9k_heavy_weaps.lua:0

[ERROR] addons/mg_m9k-master/lua/autorun/m9k_small_arms.lua:258: unfinished string near '<eof>'
1. unknown - addons/mg_m9k-master/lua/autorun/m9k_small_arms.lua:0

**Comment by Aka7tsu4** [comment]
No sounds when firing too....

**Comment by mcNuggets1** [comment]
This is not a problem coming from my addon.

You likely edited the file, just redownload.

**Comment by Aka7tsu4** [comment]
i didn't edited the file..

**Comment by mcNuggets1** [comment]
Just redownload the entire addon.

**Comment by Aka7tsu4** [comment]
okay :)
