### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by EthanAG** [mcNuggets1/mg_m9k#3]
I realize that this is in the **Issues** forum, but GitHub thought it was a smart idea to get rid of Private Messaging, I just have one thing to ask, have you tested this for compatibility with TTT servers? And if so, can you give more details on what you did?

**Comment by mcNuggets1** [comment]
This doesn't work with TTT-servers as it doesn't use any TTT functions.
These are optimised for DarkRP and Sandbox.

I've got a TTT gun base either, but it doesn't work with all weapons, so I can't upload it without getting tons of issues.
